version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Nothing to install for HTML site
  build:
    commands:
      - echo Build step for HTML - copying files
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

